# This is a GitHub actions workflow for rrfs_utl.
#
# This builds the develop branch with documentation, warning check,
# and address sanitizer.
#
# Ed Hartnett, 6/23/23
name: developer 
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

jobs:
  developer:
    runs-on: ubuntu-latest
    env:
      FC: gfortran
      CC: gcc

    strategy:
      fail-fast: true
      matrix:
        jasper-version: [4.0.0]
        bacio-version: [2.5.0]
        sp-version: [2.3.3]
        ip-version: [3.3.3]
        w3nco-version: [2.4.1]
        w3emc-version: [2.10.0]
        g2-version: [3.4.5]
        wrf_io-version: [1.2.0]
        bufr-version: [11.7.1]
        GSI-ncdiag-version: [1.1.1]

    steps:

    - name: install-dependencies
      run: |
        sudo apt-get install libmpich-dev libpng-dev zlib1g-dev libjpeg-dev libnetcdf-dev libnetcdff-dev netcdf-bin pkg-config gcovr

    - name: cache-deps
      id: cache-deps
      uses: actions/cache@v2
      with:
        path: ~/deps
        key: deps-${{ matrix.jasper-version }}-1

    - name: checkout-jasper
      if: steps.cache-deps.outputs.cache-hit != 'true'
      uses: actions/checkout@v2
      with:
        repository: jasper-software/jasper
        path: jasper
        ref: version-${{ matrix.jasper-version }}

    - name: build-jasper
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: |
        cd jasper
        mkdir b && cd b
        cmake .. -DCMAKE_INSTALL_PREFIX=~/deps
        make -j2
        make install

    - name: checkout-bacio
      if: steps.cache-deps.outputs.cache-hit != 'true'
      uses: actions/checkout@v2
      with:
        repository: NOAA-EMC/NCEPLIBS-bacio
        path: bacio
        ref: v${{ matrix.bacio-version }}
    
    - name: build-bacio
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: |
        cd bacio
        mkdir build && cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=~/deps
        make -j2
        make install

    - name: checkout-sp
      if: steps.cache-deps.outputs.cache-hit != 'true'
      uses: actions/checkout@v2
      with:
        repository: NOAA-EMC/NCEPLIBS-sp
        path: sp
        ref: v${{ matrix.sp-version }}

    - name: build-sp
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: |
        cd sp
        mkdir build
        cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=~/deps
        make -j2
        make install
          
    - name: checkout-ip
      if: steps.cache-deps.outputs.cache-hit != 'true'
      uses: actions/checkout@v2
      with:
        repository: NOAA-EMC/NCEPLIBS-ip
        path: ip
        ref: v${{ matrix.ip-version }}

    - name: build-ip
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: |
        cd ip
        mkdir build
        cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=~/deps -DCMAKE_PREFIX_PATH=~/deps
        make -j2
        make install
          
    - name: checkout-w3nco
      if: steps.cache-deps.outputs.cache-hit != 'true'
      uses: actions/checkout@v2
      with:
        repository: NOAA-EMC/NCEPLIBS-w3nco
        path: w3nco
        ref: v${{ matrix.w3nco-version }}

    - name: build-w3nco
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: |
        cd w3nco
        mkdir build
        cd build
        cmake -DCMAKE_PREFIX_PATH=~/bacio -DCMAKE_INSTALL_PREFIX=~/deps ..
        make -j2
        make install
          
    - name: checkout-w3emc
      if: steps.cache-deps.outputs.cache-hit != 'true'
      uses: actions/checkout@v2
      with:
        repository: NOAA-EMC/NCEPLIBS-w3emc
        path: w3emc
        ref: v${{ matrix.w3emc-version }}

    - name: build-w3emc
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: |
        cd w3emc
        mkdir build
        cd build
        cmake -DCMAKE_PREFIX_PATH=~/bacio -DCMAKE_INSTALL_PREFIX=~/deps -DBUILD_WITH_BUFR=OFF ..
        make -j2
        make install
          
    - name: checkout-g2
      if: steps.cache-deps.outputs.cache-hit != 'true'
      uses: actions/checkout@v2
      with:
        repository: NOAA-EMC/NCEPLIBS-g2
        path: g2
        ref: v${{ matrix.g2-version }}

    - name: build-g2
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: |
        cd g2
        mkdir build
        cd build
        cmake -DCMAKE_INSTALL_PREFIX=~/deps -DCMAKE_PREFIX_PATH=~/deps ..
        make -j2
        make install
        
    - name: checkout-wrf_io
      if: steps.cache-deps.outputs.cache-hit != 'true'
      uses: actions/checkout@v2
      with:
        repository: NOAA-EMC/NCEPLIBS-wrf_io
        path: wrf_io
        ref: v${{ matrix.wrf_io-version }}

    - name: build-wrf_io
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: |
        cd wrf_io
        mkdir build
        cd build
        cmake -DCMAKE_INSTALL_PREFIX=~/deps ..
        make -j2
        make install

    - name: checkout-bufr
      if: steps.cache-deps.outputs.cache-hit != 'true'
      uses: actions/checkout@v2
      with:
        repository: NOAA-EMC/NCEPLIBS-bufr
        path: bufr
        ref: bufr_v${{ matrix.bufr-version }}

    - name: build-bufr
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: |
        cd bufr
        mkdir build
        cd build
        cmake -DCMAKE_INSTALL_PREFIX=~/deps ..
        make -j2
        make install
        
    - name: checkout-GSI-ncdiag
      if: steps.cache-GSI-ncdiag.outputs.cache-hit != 'true'
      uses: actions/checkout@v2
      with:
        repository: NOAA-EMC/GSI-ncdiag
        path: gsi-ncdiag
        ref: v${{ matrix.GSI-ncdiag-version }}

    - name: build-GSI-ncdiag
      if: steps.cache-GSI-ncdiag.outputs.cache-hit != 'true'
      run: |
        cd gsi-ncdiag
        mkdir build
        cd build
        cmake -DCMAKE_INSTALL_PREFIX=~/deps -DCMAKE_PREFIX_PATH=~/deps .. 
        make -j2
        make install
        
        
